export interface CanvasBrowserRegressionSite {
  readonly id: number;
  readonly category: string;
  readonly site: string;
  readonly representativeTask: string;
}

export const CANVAS_BROWSER_REGRESSION_SITES: readonly CanvasBrowserRegressionSite[] = [
  { id: 1, category: "Literature", site: "https://pubmed.ncbi.nlm.nih.gov", representativeTask: "Search a biomedical question, open an abstract, export citation" },
  { id: 2, category: "Literature", site: "https://pmc.ncbi.nlm.nih.gov", representativeTask: "Find an open-access paper, open figures, download PDF" },
  { id: 3, category: "Literature", site: "https://scholar.google.com", representativeTask: "Search a paper title, inspect cited-by links" },
  { id: 4, category: "Literature", site: "https://www.semanticscholar.org", representativeTask: "Search author/topic, save/export paper metadata" },
  { id: 5, category: "Literature", site: "https://openalex.org", representativeTask: "Search works/authors/institutions, inspect metadata" },
  { id: 6, category: "Literature", site: "https://www.crossref.org", representativeTask: "Find DOI metadata for a paper" },
  { id: 7, category: "Literature", site: "https://www.biorxiv.org", representativeTask: "Search preprints, filter by subject area" },
  { id: 8, category: "Literature", site: "https://www.medrxiv.org", representativeTask: "Search clinical preprints, open PDF" },
  { id: 9, category: "Literature", site: "https://arxiv.org", representativeTask: "Search paper, open abstract, download source/PDF" },
  { id: 10, category: "Literature", site: "https://www.researchsquare.com", representativeTask: "Search preprints, inspect article page" },
  { id: 11, category: "Publishers", site: "https://www.nature.com", representativeTask: "Search research article, open figures/supplement" },
  { id: 12, category: "Publishers", site: "https://www.science.org", representativeTask: "Search article, handle publisher layout" },
  { id: 13, category: "Publishers", site: "https://www.cell.com", representativeTask: "Open article page, find figures and supplementary data" },
  { id: 14, category: "Publishers", site: "https://www.thelancet.com", representativeTask: "Search clinical article, inspect abstract/figures" },
  { id: 15, category: "Publishers", site: "https://www.nejm.org", representativeTask: "Search clinical paper, inspect article page" },
  { id: 16, category: "Publishers", site: "https://journals.plos.org/plosone", representativeTask: "Search article, download citation/PDF" },
  { id: 17, category: "Publishers", site: "https://elifesciences.org", representativeTask: "Open article, navigate figures and decision letter" },
  { id: 18, category: "Publishers", site: "https://bmj.com", representativeTask: "Search clinical topic, open article" },
  { id: 19, category: "Publishers", site: "https://jamanetwork.com", representativeTask: "Search article, inspect abstract" },
  { id: 20, category: "Publishers", site: "https://www.frontiersin.org", representativeTask: "Search journal article, inspect sections" },
  { id: 21, category: "Data Repository", site: "https://zenodo.org", representativeTask: "Search dataset, inspect files, download metadata" },
  { id: 22, category: "Data Repository", site: "https://dataverse.harvard.edu", representativeTask: "Search dataset, inspect file table" },
  { id: 23, category: "Data Repository", site: "https://datadryad.org", representativeTask: "Search dataset, inspect associated paper" },
  { id: 24, category: "Data Repository", site: "https://figshare.com", representativeTask: "Search dataset, inspect file downloads" },
  { id: 25, category: "Data Repository", site: "https://osf.io", representativeTask: "Open project, navigate files/wiki/registrations" },
  { id: 26, category: "Data Repository", site: "https://data.mendeley.com", representativeTask: "Search dataset, inspect files" },
  { id: 27, category: "Data Repository", site: "https://www.synapse.org", representativeTask: "Search biomedical dataset, inspect access conditions" },
  { id: 28, category: "Data Repository", site: "https://www.kaggle.com/datasets", representativeTask: "Search scientific dataset, inspect files/notebooks" },
  { id: 29, category: "Data Repository", site: "https://huggingface.co/datasets", representativeTask: "Search dataset, preview files/cards" },
  { id: 30, category: "Data Repository", site: "https://github.com", representativeTask: "Open scientific repo, inspect README/issues/releases" },
  { id: 31, category: "Clinical", site: "https://clinicaltrials.gov", representativeTask: "Search condition, filter trial status, open trial record" },
  { id: 32, category: "Clinical", site: "https://www.who.int/clinical-trials-registry-platform", representativeTask: "Find clinical trial registry info" },
  { id: 33, category: "Clinical", site: "https://www.cochranelibrary.com", representativeTask: "Search systematic review, inspect abstract" },
  { id: 34, category: "Clinical", site: "https://www.tripdatabase.com", representativeTask: "Search evidence summary" },
  { id: 35, category: "Clinical", site: "https://www.guidelinecentral.com", representativeTask: "Search clinical guideline" },
  { id: 36, category: "Clinical", site: "https://www.ncbi.nlm.nih.gov/books", representativeTask: "Search NCBI Bookshelf clinical/science reference" },
  { id: 37, category: "Clinical", site: "https://www.omim.org", representativeTask: "Search gene/disease entry" },
  { id: 38, category: "Clinical", site: "https://www.orpha.net", representativeTask: "Search rare disease" },
  { id: 39, category: "Clinical", site: "https://www.pharmgkb.org", representativeTask: "Search gene-drug relationship" },
  { id: 40, category: "Clinical", site: "https://www.clinicalgenome.org", representativeTask: "Search gene/disease validity" },
  { id: 41, category: "Genomics", site: "https://www.ncbi.nlm.nih.gov/geo", representativeTask: "Search GEO accession, inspect samples, download series matrix" },
  { id: 42, category: "Genomics", site: "https://www.ncbi.nlm.nih.gov/sra", representativeTask: "Search SRA run, inspect metadata" },
  { id: 43, category: "Genomics", site: "https://www.ncbi.nlm.nih.gov/gene", representativeTask: "Search gene, inspect summary and links" },
  { id: 44, category: "Genomics", site: "https://blast.ncbi.nlm.nih.gov", representativeTask: "Run or inspect BLAST form behavior" },
  { id: 45, category: "Genomics", site: "https://www.ncbi.nlm.nih.gov/clinvar", representativeTask: "Search variant, inspect clinical significance" },
  { id: 46, category: "Genomics", site: "https://www.ncbi.nlm.nih.gov/snp", representativeTask: "Search dbSNP rsID" },
  { id: 47, category: "Genomics", site: "https://www.ncbi.nlm.nih.gov/assembly", representativeTask: "Search genome assembly" },
  { id: 48, category: "Genomics", site: "https://www.ensembl.org", representativeTask: "Search gene, inspect genome browser" },
  { id: 49, category: "Genomics", site: "https://genome.ucsc.edu", representativeTask: "Use genome browser, search gene/coordinate" },
  { id: 50, category: "Genomics", site: "https://gnomad.broadinstitute.org", representativeTask: "Search variant/gene, inspect population frequencies" },
  { id: 51, category: "Cancer Biology", site: "https://portal.gdc.cancer.gov", representativeTask: "Search cancer dataset, inspect cases/files" },
  { id: 52, category: "Cancer Biology", site: "https://www.cbioportal.org", representativeTask: "Open cancer study, inspect mutations/survival plots" },
  { id: 53, category: "Cancer Biology", site: "https://xenabrowser.net", representativeTask: "Explore TCGA-style dataset" },
  { id: 54, category: "Cancer Biology", site: "https://depmap.org/portal", representativeTask: "Search cell line/gene dependency" },
  { id: 55, category: "Cancer Biology", site: "https://www.proteinatlas.org", representativeTask: "Search gene, inspect tissue/cancer expression" },
  { id: 56, category: "Proteins", site: "https://www.uniprot.org", representativeTask: "Search protein, inspect function and sequences" },
  { id: 57, category: "Proteins", site: "https://www.rcsb.org", representativeTask: "Search protein structure, view/download PDB" },
  { id: 58, category: "Proteins", site: "https://alphafold.ebi.ac.uk", representativeTask: "Search protein structure prediction" },
  { id: 59, category: "Proteins", site: "https://www.ebi.ac.uk/interpro", representativeTask: "Search protein domain" },
  { id: 60, category: "Proteins", site: "https://www.expasy.org", representativeTask: "Search bioinformatics resource/tool" },
  { id: 61, category: "Pathways", site: "https://reactome.org", representativeTask: "Search pathway/gene, inspect pathway diagram" },
  { id: 62, category: "Pathways", site: "https://www.genome.jp/kegg", representativeTask: "Search pathway, navigate map" },
  { id: 63, category: "Pathways", site: "https://string-db.org", representativeTask: "Search protein interaction network" },
  { id: 64, category: "Pathways", site: "https://thebiogrid.org", representativeTask: "Search interaction database" },
  { id: 65, category: "Pathways", site: "https://opentargets.org", representativeTask: "Search target/disease association" },
  { id: 66, category: "Single Cell", site: "https://cellxgene.cziscience.com", representativeTask: "Search cell atlas dataset, inspect explorer" },
  { id: 67, category: "Single Cell", site: "https://www.humancellatlas.org", representativeTask: "Find data portal/project" },
  { id: 68, category: "Single Cell", site: "https://portal.hubmapconsortium.org", representativeTask: "Search tissue dataset" },
  { id: 69, category: "Single Cell", site: "https://singlecell.broadinstitute.org/single_cell", representativeTask: "Search single-cell study" },
  { id: 70, category: "Single Cell", site: "https://www.ebi.ac.uk/gxa/sc/home", representativeTask: "Search single-cell expression atlas" },
  { id: 71, category: "Neuroscience", site: "https://dandiarchive.org", representativeTask: "Search neurophysiology dataset, inspect assets" },
  { id: 72, category: "Neuroscience", site: "https://openneuro.org", representativeTask: "Search MRI/fMRI dataset, inspect files" },
  { id: 73, category: "Neuroscience", site: "https://physionet.org", representativeTask: "Search physiological dataset, inspect files/citation" },
  { id: 74, category: "Neuroscience", site: "https://neurovault.org", representativeTask: "Search brain map collection" },
  { id: 75, category: "Neuroscience", site: "https://neuromorpho.org", representativeTask: "Search neuron morphology" },
  { id: 76, category: "Neuroscience", site: "https://portal.brain-map.org", representativeTask: "Search Allen Brain Atlas data" },
  { id: 77, category: "Neuroscience", site: "https://www.braininitiative.org", representativeTask: "Find BRAIN Initiative resources" },
  { id: 78, category: "Neuroscience", site: "https://www.nitrc.org", representativeTask: "Search neuroimaging tool/resource" },
  { id: 79, category: "Neuroscience", site: "https://bids.neuroimaging.io", representativeTask: "Navigate BIDS standard docs" },
  { id: 80, category: "Neuroscience", site: "https://www.humanconnectome.org", representativeTask: "Find HCP dataset info" },
  { id: 81, category: "Chemistry", site: "https://pubchem.ncbi.nlm.nih.gov", representativeTask: "Search compound, inspect structure/properties" },
  { id: 82, category: "Chemistry", site: "https://www.chemspider.com", representativeTask: "Search compound" },
  { id: 83, category: "Chemistry", site: "https://www.ebi.ac.uk/chembl", representativeTask: "Search bioactive molecule" },
  { id: 84, category: "Chemistry", site: "https://zinc.docking.org", representativeTask: "Search purchasable compound" },
  { id: 85, category: "Chemistry", site: "https://www.rcsb.org/ligand", representativeTask: "Search ligand" },
  { id: 86, category: "Chemistry", site: "https://go.drugbank.com", representativeTask: "Search drug page" },
  { id: 87, category: "Chemistry", site: "https://www.bindingdb.org", representativeTask: "Search binding data" },
  { id: 88, category: "Chemistry", site: "https://www.sigmaaldrich.com", representativeTask: "Search reagent/product/SDS" },
  { id: 89, category: "Chemistry", site: "https://www.thermofisher.com", representativeTask: "Search reagent/protocol/product page" },
  { id: 90, category: "Chemistry", site: "https://www.addgene.org", representativeTask: "Search plasmid, inspect map/depositor info" },
  { id: 91, category: "Protocols", site: "https://www.protocols.io", representativeTask: "Search protocol, inspect steps/materials" },
  { id: 92, category: "Protocols", site: "https://www.jove.com", representativeTask: "Search experimental method video/article" },
  { id: 93, category: "Protocols", site: "https://www.bio-protocol.org", representativeTask: "Search protocol article" },
  { id: 94, category: "Protocols", site: "https://benchling.com", representativeTask: "Exercise login/landing/docs style workflows" },
  { id: 95, category: "Protocols", site: "https://www.labarchives.com", representativeTask: "Exercise ELN-style navigation" },
  { id: 96, category: "Environment", site: "https://earthdata.nasa.gov", representativeTask: "Search Earth science data" },
  { id: 97, category: "Environment", site: "https://data.noaa.gov", representativeTask: "Search climate/ocean dataset" },
  { id: 98, category: "Environment", site: "https://waterdata.usgs.gov", representativeTask: "Search water monitoring data" },
  { id: 99, category: "Environment", site: "https://www.gbif.org", representativeTask: "Search species occurrence data" },
  { id: 100, category: "Environment", site: "https://www.worldclim.org", representativeTask: "Find climate raster dataset" },
] as const;
