/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as PapersIndexRouteImport } from './routes/papers.index'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as PapersPaperIdRouteImport } from './routes/papers.$paperId'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PapersRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: '/$paperId',
  path: '/$paperId',
  getParentRoute: () => PapersRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/datasets': typeof DatasetsRoute
  '/papers': typeof PapersRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/papers/': typeof PapersIndexRoute
}
export interface FileRoutesByTo {
  '/datasets': typeof DatasetsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/papers': typeof PapersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/datasets': typeof DatasetsRoute
  '/papers': typeof PapersRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/papers/': typeof PapersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets'
    | '/papers'
    | '/settings'
    | '/$threadId'
    | '/papers/$paperId'
    | '/settings/archived'
    | '/settings/general'
    | '/papers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/datasets'
    | '/settings'
    | '/$threadId'
    | '/papers/$paperId'
    | '/settings/archived'
    | '/settings/general'
    | '/'
    | '/papers'
  id:
    | '__root__'
    | '/_chat'
    | '/datasets'
    | '/papers'
    | '/settings'
    | '/_chat/$threadId'
    | '/papers/$paperId'
    | '/settings/archived'
    | '/settings/general'
    | '/_chat/'
    | '/papers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  DatasetsRoute: typeof DatasetsRoute
  PapersRoute: typeof PapersRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/': {
      id: '/papers/'
      path: '/'
      fullPath: '/papers/'
      preLoaderRoute: typeof PapersIndexRouteImport
      parentRoute: typeof PapersRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/papers/$paperId': {
      id: '/papers/$paperId'
      path: '/$paperId'
      fullPath: '/papers/$paperId'
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof PapersRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface PapersRouteChildren {
  PapersPaperIdRoute: typeof PapersPaperIdRoute
  PapersIndexRoute: typeof PapersIndexRoute
}

const PapersRouteChildren: PapersRouteChildren = {
  PapersPaperIdRoute: PapersPaperIdRoute,
  PapersIndexRoute: PapersIndexRoute,
}

const PapersRouteWithChildren =
  PapersRoute._addFileChildren(PapersRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  DatasetsRoute: DatasetsRoute,
  PapersRoute: PapersRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
